# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "bookteria_services"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8888"
          - "host.docker.internal:8761"
          - "host.docker.internal:9000"
          - "host.docker.internal:8080"
          - "host.docker.internal:8081"
          - "host.docker.internal:8082"